In [8]:
import numpy as np
import pandas as pd
from tqdm import tqdm
from random import sample

In [9]:
train_data = pd.read_csv('train.csv', sep=',')  # 训练数据
train_data_matrix = np.zeros((2967, 4125))  # 训练数据矩阵
for line in train_data.itertuples():
    train_data_matrix[line[1], line[2]] = line[3]

In [10]:
def get_dict_u():
    dict1 = {}#不同user各自对应的item
    dict2 = {}#不同item各自对应的user
    for i in range(2967):
        dict1[i] = []

        for j in range(4125):
            if train_data_matrix[i][j] != 0:
                dict1[i].append(j)
                if j not in dict2.keys():
                    dict2[j] = []
                dict2[j].append(i)
    return [dict1, dict2]

In [1]:
# K=10,alpha=0.01,lbd = 0.3,miu = 0.1,bu = 0.1,bm = 0.1; rsme = 0.93
# K = 30,alpha = 0.01,lbd = 0.3,miu = 0.1,bu = 0.1,bm = 0.1;rsme = 0.98
# K = 30，alpha = 0.01，lbd = 0.3，miu = 0.2，bu = 0.1，bm = 0.1；rsme = 0.91
# K = 40，alpha = 0.01，lbd = 0.3，miu = 0.3，bu = 0.1，bm = 0.1；rsme = 0.92
# K = 40,alpha = 0.01,lbd = 0.3,miu = 0.25,bu = 0.1bm = 0.1,;rsme = 0.92
# K = 20,alpha = 0.01,lbd = 0.3,miu = 0.2,bu = 0.1,bm = 0.1;rsme = 0.89
# K = 15,alpha = 0.01,lbd = 0.3,miu = 0.2,bu = 0.1,bm = 0.1;rsme = 0.898
# K = 10,alpha = 0.01,lbd = 0.3,miu = 0.2,bu = 0.1,bm = 0.1;for(35);rsme = 0.89
# K = 10,alpha = 0.01,lbd = 0.3,miu = 0.15,bu = 0.1,bm = 0.1;for(35);rsme = 0.90
# K = 30,alpha = 0.01,lbd = 0.3,miu = 0.15,bu = 0.1,bm = 0.1;for(20)；rsme = 0.89
# K = 10,alpha = 0.01,lbd = 0.3,miu = 0.15,bu = 0.1,bm = 0.1;for(35)

In [50]:
K = 30
alpha = 0.01
lbd = 0.3
miu = 0.2
bu = 0.1
bm = 0.1
F = np.random.rand(2967,K)
G = np.random.rand(4125,K)

lis = get_dict_u()

In [56]:
for z in tqdm(range(20)):
    for i in lis[0].keys():
        for j in lis[0][i]:
            F[i] = (1-alpha*lbd)*F[i] + alpha*G[j]*(train_data_matrix[i][j] - (miu + bu + bm + np.dot(F[i],(G[j].T))))
            G[j] = (1-alpha*lbd)*G[j] + alpha*F[i]*(train_data_matrix[i][j] - (miu + bu + bm + np.dot(F[i],(G[j].T))))
            bu = (1-alpha*lbd)*bu + alpha*(train_data_matrix[i][j] - (miu + bu + bm +np.dot(F[i],(G[j].T))))
            bm = (1-alpha*lbd)*bm + alpha*(train_data_matrix[i][j] - (miu + bu + bm + np.dot(F[i],(G[j].T))))
            # print(F[i])
            # print(G[j])
            # F[i] = fi
            # G[j] = gj
            # bu = bu_t
            # bm = bm_t
    print(F)
    print(G)

    print(np.dot(F,G.T) + miu + bu + bm)
    res = np.dot(F,G.T) + miu + bu + bm
    df = pd.read_csv("test_index.csv")
    test_data_matrix = df.values

    predict_matrix = np.zeros((39679, 2))

    f = open('predict2.csv','w')
    f.write('dataID,rating\n')
    for i in range(test_data_matrix.shape[0]):
        predict_matrix[i][0] = i
        predict_matrix[i][1] = res[test_data_matrix[i][0]][test_data_matrix[i][1]]
        f.write('%d,%.8f\n'%(predict_matrix[i][0],predict_matrix[i][1]))

  0%|          | 0/20 [00:00<?, ?it/s]

[[0.11696308 0.17312134 0.18805298 ... 0.25282806 0.22942513 0.1405728 ]
 [0.10571077 0.12687509 0.14727138 ... 0.18408553 0.15411249 0.14627632]
 [0.13513574 0.14705666 0.1623079  ... 0.12763915 0.14467535 0.11867155]
 ...
 [0.27460679 0.25263509 0.22905562 ... 0.21163861 0.23833268 0.23750583]
 [0.33975416 0.22264311 0.2447329  ... 0.36267033 0.2944282  0.23310791]
 [0.14387286 0.11794651 0.0872906  ... 0.11477544 0.14827497 0.21504723]]
[[ 0.17676218  0.19737613  0.23634819 ...  0.26768864  0.23895134
   0.24871037]
 [ 0.13973428  0.16296528  0.18420361 ...  0.16803012  0.18804381
   0.16702316]
 [ 0.21836775  0.23316799  0.25750096 ...  0.27593922  0.28658496
   0.26486143]
 ...
 [ 0.41263763  0.12184661  0.43762542 ...  0.82412569  0.26019796
   0.59807725]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.26805397 -0.15460955  0.23006471 ... -0.17330118 -0.05718845
  -0.14425497]]
[[3.32539769 3.05429168 3.46964678 ... 4.40046801 4.62127351 2.8

  5%|▌         | 1/20 [00:02<00:43,  2.27s/it]

[[0.11593624 0.17204236 0.18821159 ... 0.2526619  0.22892779 0.14144574]
 [0.10520403 0.12711564 0.14695049 ... 0.18391345 0.15404262 0.14616687]
 [0.13536763 0.14727377 0.16142939 ... 0.12751558 0.14386257 0.11836724]
 ...
 [0.27473624 0.25274237 0.22886643 ... 0.21138769 0.23795606 0.23714091]
 [0.33927564 0.22396504 0.24474554 ... 0.36076321 0.29339739 0.2336602 ]
 [0.14381114 0.11776065 0.08771648 ... 0.1150288  0.14853896 0.21490608]]
[[ 0.17597889  0.1968766   0.23630167 ...  0.26813702  0.23937569
   0.24897811]
 [ 0.13991996  0.16320993  0.18410007 ...  0.16801761  0.18797507
   0.16684998]
 [ 0.21803868  0.23296019  0.25754644 ...  0.27603429  0.28664059
   0.26495408]
 ...
 [ 0.41197147  0.12208261  0.43692412 ...  0.82229681  0.26006502
   0.59698891]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.26574238 -0.15575707  0.22775879 ... -0.1745055  -0.05874543
  -0.14571094]]
[[3.32632957 3.05415274 3.46977818 ... 4.3969421  4.62134931 2.8

 10%|█         | 2/20 [00:04<00:40,  2.28s/it]

[[0.11491744 0.17098398 0.18836086 ... 0.25251735 0.22845145 0.14230521]
 [0.10471019 0.12734963 0.14664117 ... 0.18375142 0.15397876 0.14605901]
 [0.13559527 0.14749744 0.16057089 ... 0.12738914 0.14307115 0.11805852]
 ...
 [0.27486425 0.25284892 0.2286781  ... 0.21113391 0.23758171 0.23677682]
 [0.33881253 0.22526269 0.2447606  ... 0.35888177 0.29237921 0.23419664]
 [0.14374293 0.1175811  0.08813984 ... 0.11527664 0.14879476 0.21476247]]
[[ 0.1752023   0.19638165  0.23625734 ...  0.26858287  0.2397965
   0.2492443 ]
 [ 0.14010369  0.16345382  0.1839979  ...  0.16800509  0.1879073
   0.16668146]
 [ 0.21771296  0.23275571  0.25759121 ...  0.27612969  0.2866959
   0.26504628]
 ...
 [ 0.41130119  0.12231135  0.43621955 ...  0.82046756  0.25992659
   0.59589698]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.26345485 -0.15688216  0.2254751  ... -0.1756889  -0.06028054
  -0.1471425 ]]
[[3.32727435 3.05400741 3.46991318 ... 4.39338032 4.62142345 2.8531

 15%|█▌        | 3/20 [00:06<00:38,  2.27s/it]

[[0.11390642 0.16994549 0.18850122 ... 0.25239352 0.22799541 0.14315152]
 [0.10422872 0.12757722 0.14634299 ... 0.18359896 0.15392056 0.14595274]
 [0.1358186  0.14772724 0.15973177 ... 0.12726001 0.14230048 0.11774565]
 ...
 [0.2749907  0.25295461 0.22849069 ... 0.21087755 0.23720974 0.2364137 ]
 [0.3383644  0.22653654 0.24477791 ... 0.35702559 0.29137351 0.23471757]
 [0.14366847 0.11740764 0.08856071 ... 0.11551909 0.14904265 0.21461645]]
[[ 0.17443271  0.19589145  0.23621507 ...  0.26902587  0.2402136
   0.24950869]
 [ 0.14028547  0.16369689  0.18389705 ...  0.16799258  0.18784048
   0.16651748]
 [ 0.21739069  0.23255458  0.25763522 ...  0.27622527  0.2867508
   0.26513791]
 ...
 [ 0.41062688  0.12253296  0.43551176 ...  0.81863799  0.25978275
   0.59480155]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.26119117 -0.15798505  0.22321349 ... -0.17685154 -0.06179391
  -0.14854986]]
[[3.32823147 3.05385572 3.47005149 ... 4.38978356 4.62149553 2.841

 20%|██        | 4/20 [00:09<00:36,  2.26s/it]

[[0.11290297 0.16892623 0.18863309 ... 0.25228957 0.22755901 0.14398496]
 [0.10375911 0.12779859 0.14605552 ... 0.18345561 0.15386769 0.14584804]
 [0.13603753 0.14796271 0.15891145 ... 0.12712836 0.14154997 0.11742886]
 ...
 [0.27511545 0.25305933 0.22830424 ... 0.21061888 0.23684025 0.23605165]
 [0.3379308  0.22778705 0.24479731 ... 0.35519425 0.29038015 0.23522331]
 [0.14358795 0.11724011 0.08897906 ... 0.11575627 0.14928288 0.21446808]]
[[ 0.17367042  0.19540619  0.23617474 ...  0.26946572  0.24062682
   0.24977104]
 [ 0.14046529  0.16393907  0.18379748 ...  0.16798011  0.18777457
   0.16635791]
 [ 0.21707197  0.23235688  0.25767844 ...  0.27632086  0.2868052
   0.26522886]
 ...
 [ 0.40994864  0.12274754  0.43480084 ...  0.8168082   0.25963358
   0.59370274]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.25895112 -0.15906597  0.22097385 ... -0.17799358 -0.06328571
  -0.14993324]]
[[3.32920034 3.05369772 3.47019279 ... 4.38615275 4.62156521 2.82

 25%|██▌       | 5/20 [00:11<00:33,  2.24s/it]

[[0.1119069  0.16792559 0.18875684 ... 0.25220464 0.22714158 0.14480582]
 [0.10330091 0.12801389 0.14577838 ... 0.1833209  0.15381982 0.1457449 ]
 [0.13625197 0.14820342 0.15810937 ... 0.1269944  0.14081909 0.11710841]
 ...
 [0.27523839 0.25316296 0.22811879 ... 0.21035815 0.23647332 0.23569081]
 [0.33751131 0.22901468 0.24481863 ... 0.35338735 0.28939898 0.23571418]
 [0.14350159 0.11707831 0.08939491 ... 0.11598831 0.14951568 0.21431742]]
[[ 0.17291571  0.19492603  0.23613621 ...  0.26990215  0.241036
   0.25003112]
 [ 0.14064313  0.16418033  0.18369917 ...  0.1679677   0.18770955
   0.16620264]
 [ 0.2167569   0.23216267  0.25772083 ...  0.2764163   0.28685902
   0.26531903]
 ...
 [ 0.40926658  0.12295521  0.43408686 ...  0.81497825  0.25947917
   0.59260064]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.2567345  -0.16012515  0.21875604 ... -0.17911519 -0.06475607
  -0.15129287]]
[[3.33018038 3.05353346 3.4703368  ... 4.38248881 4.62163216 2.817

 30%|███       | 6/20 [00:13<00:31,  2.24s/it]

[[0.11091803 0.16694297 0.18887286 ... 0.25213793 0.2267425  0.14561434]
 [0.10285367 0.12822327 0.14551118 ... 0.18319442 0.15377667 0.14564329]
 [0.13646185 0.14844896 0.15732498 ... 0.12685831 0.14010728 0.11678456]
 ...
 [0.27535941 0.25326539 0.2279344  ... 0.21009562 0.23610905 0.2353313 ]
 [0.33710549 0.23021986 0.24484175 ... 0.35160448 0.28842986 0.23619049]
 [0.14340959 0.11692206 0.08980825 ... 0.11621531 0.14974129 0.21416451]]
[[ 0.17216885  0.19445115  0.23609938 ...  0.27033487  0.24144098
   0.25028872]
 [ 0.14081899  0.1644206   0.18360206 ...  0.16795537  0.1876454
   0.16605155]
 [ 0.21644556  0.23197198  0.25776234 ...  0.27651145  0.28691218
   0.2654083 ]
 ...
 [ 0.4085808   0.12315609  0.4333699  ...  0.81314822  0.25931961
   0.59149536]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.2545411  -0.1611628   0.21655995 ... -0.18021654 -0.06620515
  -0.15262895]]
[[3.33117096 3.05336302 3.47048322 ... 4.37879269 4.62169607 2.80

 35%|███▌      | 7/20 [00:15<00:29,  2.23s/it]

[[0.10993621 0.16597781 0.18898149 ... 0.25208864 0.22636113 0.14641078]
 [0.10241695 0.12842688 0.14525355 ... 0.18307575 0.15373795 0.1455432 ]
 [0.13666708 0.14869893 0.15655775 ... 0.12672028 0.13941405 0.11645753]
 ...
 [0.27547838 0.2533665  0.2277511  ... 0.20983154 0.23574752 0.23497321]
 [0.33671295 0.23140302 0.24486651 ... 0.34984528 0.28747265 0.23665256]
 [0.14331214 0.11677119 0.09021908 ... 0.11643738 0.14995994 0.21400943]]
[[ 0.1714301   0.1939817   0.23606413 ...  0.27076362  0.24184161
   0.25054362]
 [ 0.14099285  0.16465983  0.18350614 ...  0.16794316  0.18758208
   0.16590454]
 [ 0.21613805  0.23178487  0.25780295 ...  0.27660614  0.2869646
   0.26549658]
 ...
 [ 0.4078914   0.12335028  0.43265002 ...  0.81131819  0.25915498
   0.59038701]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.2523707  -0.16217917  0.21438542 ... -0.18129779 -0.0676331
  -0.15394171]]
[[3.33217147 3.05318648 3.47063178 ... 4.37506533 4.62175664 2.794

 40%|████      | 8/20 [00:17<00:26,  2.22s/it]

[[0.10896133 0.16502959 0.18908308 ... 0.25205599 0.22599687 0.14719538]
 [0.10199036 0.12862488 0.14500514 ... 0.18296448 0.15370337 0.14544459]
 [0.13686759 0.14895294 0.15580719 ... 0.12658051 0.13873891 0.11612759]
 ...
 [0.2755952  0.25346619 0.22756894 ... 0.20956614 0.23538882 0.23461668]
 [0.33633329 0.23256458 0.2448928  ... 0.34810937 0.28652721 0.2371007 ]
 [0.14320945 0.11662555 0.0906274  ... 0.11665464 0.15017185 0.21385223]]
[[ 0.17069971  0.19351784  0.23603034 ...  0.27118814  0.24223775
   0.25079564]
 [ 0.14116469  0.16489797  0.18341137 ...  0.16793108  0.18751959
   0.16576149]
 [ 0.21583444  0.23160138  0.25784264 ...  0.27670025  0.28701621
   0.26558378]
 ...
 [ 0.40719848  0.12353791  0.43192731 ...  0.80948824  0.25898538
   0.5892757 ]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.25022309 -0.16317447  0.21223234 ... -0.1823591  -0.06904006
  -0.15523135]]
[[3.33318125 3.05300396 3.4707822  ... 4.37130769 4.62181359 2.7

 45%|████▌     | 9/20 [00:20<00:24,  2.20s/it]

[[0.10799327 0.16409781 0.18917795 ... 0.25203922 0.22564913 0.14796834]
 [0.10157352 0.12881741 0.1447656  ... 0.18286024 0.15367267 0.14534744]
 [0.13706331 0.14921061 0.15507281 ... 0.12643918 0.13808137 0.11579496]
 ...
 [0.27570976 0.25356436 0.22738795 ... 0.20929965 0.23503301 0.23426179]
 [0.3359661  0.23370494 0.2449205  ... 0.34639637 0.28559341 0.23753522]
 [0.14310171 0.11648495 0.0910332  ... 0.1168672  0.15037722 0.21369297]]
[[ 0.16997793  0.19305972  0.23599792 ...  0.27160818  0.24262926
   0.25104458]
 [ 0.1413345   0.16513496  0.18331771 ...  0.16791917  0.18745789
   0.16562232]
 [ 0.21553482  0.23142157  0.25788136 ...  0.27679365  0.28706694
   0.26566981]
 ...
 [ 0.40650215  0.12371909  0.43120186 ...  0.80765845  0.25881089
   0.58816153]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.24809808 -0.16414894  0.21010057 ... -0.18340064 -0.0704262
  -0.1564981 ]]
[[3.33419967 3.05281557 3.47093424 ... 4.36752074 4.62186668 2.77

 50%|█████     | 10/20 [00:22<00:22,  2.21s/it]

[[0.10703195 0.163182   0.1892664  ... 0.2520376  0.22531734 0.14872988]
 [0.10116607 0.12900462 0.1445346  ... 0.18276266 0.15364561 0.14525171]
 [0.13725415 0.14947159 0.15435413 ... 0.1262965  0.137441   0.1154599 ]
 ...
 [0.27582197 0.25366092 0.22720816 ... 0.20903229 0.23468018 0.23390866]
 [0.33561101 0.23482448 0.24494948 ... 0.34470595 0.28467113 0.23795641]
 [0.14298911 0.11634925 0.09143649 ... 0.11707515 0.15057626 0.2135317 ]]
[[ 0.16926498  0.19260747  0.23596675 ...  0.27202353  0.24301601
   0.25129027]
 [ 0.14150227  0.16537077  0.18322514 ...  0.16790745  0.18739698
   0.16548692]
 [ 0.21523927  0.23124545  0.25791911 ...  0.2768862   0.28711673
   0.2657546 ]
 ...
 [ 0.40580251  0.12389395  0.43047373 ...  0.80582891  0.25863162
   0.58704462]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.24599543 -0.16510279  0.20798999 ... -0.18442257 -0.07179165
  -0.15774215]]
[[3.33522606 3.05262143 3.47108762 ... 4.36370546 4.62191568 2.7

 55%|█████▌    | 11/20 [00:24<00:19,  2.20s/it]

[[0.10607729 0.16228172 0.18934872 ... 0.25205042 0.22500093 0.1494802 ]
 [0.10076766 0.12918663 0.14431182 ... 0.18267137 0.15362195 0.14515736]
 [0.13744004 0.14973552 0.15365072 ... 0.12615265 0.13681736 0.11512265]
 ...
 [0.27593173 0.25375577 0.22702962 ... 0.20876428 0.23433039 0.23355738]
 [0.33526765 0.23592359 0.24497964 ... 0.34303776 0.28376022 0.23836457]
 [0.14287182 0.11621829 0.09183726 ... 0.11727859 0.15076917 0.21336849]]
[[ 0.16856108  0.19216123  0.23593675 ...  0.27243397  0.24339786
   0.25153255]
 [ 0.14166798  0.16560533  0.18313364 ...  0.16789595  0.18733684
   0.16535519]
 [ 0.21494784  0.23107308  0.25795585 ...  0.27697779  0.28716551
   0.26583806]
 ...
 [ 0.40509968  0.12406259  0.42974302 ...  0.80399969  0.25844765
   0.58592508]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.24391496 -0.16603625  0.20590045 ... -0.18542506 -0.07313657
  -0.15896373]]
[[3.33625975 3.0524217  3.47124211 ... 4.35986283 4.62196037 2.7

 60%|██████    | 12/20 [00:26<00:17,  2.25s/it]

[[0.10512925 0.16139656 0.18942521 ... 0.25207697 0.22469936 0.15021949]
 [0.10037797 0.1293636  0.14409695 ... 0.18258605 0.15360145 0.14506436]
 [0.13762092 0.15000207 0.15296214 ... 0.12600781 0.13621004 0.11478343]
 ...
 [0.27603895 0.25384883 0.22685235 ... 0.20849581 0.23398371 0.23320805]
 [0.33493564 0.23700264 0.24501088 ... 0.34139145 0.28286058 0.23876001]
 [0.14275003 0.11609192 0.09223551 ... 0.11747763 0.15095614 0.2132034 ]]
[[ 0.16786642  0.19172111  0.23590782 ...  0.27283928  0.24377472
   0.25177128]
 [ 0.14183161  0.16583861  0.18304317 ...  0.16788469  0.18727746
   0.16522707]
 [ 0.21466061  0.23090447  0.25799158 ...  0.27706831  0.28721324
   0.26592012]
 ...
 [ 0.40439375  0.12422515  0.42900981 ...  0.80217089  0.25825909
   0.58480301]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.24185644 -0.16694955  0.20383182 ... -0.18640827 -0.07446113
  -0.16016304]]
[[3.33730008 3.05221651 3.47139745 ... 4.35599385 4.62200054 2.7

 65%|██████▌   | 13/20 [00:29<00:15,  2.27s/it]

[[0.10418776 0.16052612 0.18949612 ... 0.25211658 0.2244121  0.15094792]
 [0.09999669 0.12953566 0.1438897  ... 0.18250636 0.1535839  0.14497266]
 [0.13779671 0.15027092 0.15228797 ... 0.12586218 0.13561863 0.11444247]
 ...
 [0.27614355 0.25394002 0.22667638 ... 0.20822709 0.2336402  0.23286075]
 [0.33461464 0.23806199 0.24504312 ... 0.33976672 0.28197208 0.23914302]
 [0.14262391 0.11596999 0.09263122 ... 0.11767236 0.15113736 0.21303649]]
[[ 0.1671812   0.19128724  0.23587986 ...  0.27323928  0.24414647
   0.25200631]
 [ 0.14199314  0.16607056  0.18295372 ...  0.16787371  0.18721883
   0.16510244]
 [ 0.21437764  0.23073966  0.25802627 ...  0.27715766  0.28725985
   0.26600071]
 ...
 [ 0.40368483  0.12438174  0.42827418 ...  0.80034259  0.25806603
   0.58367854]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.23981968 -0.1678429   0.20178398 ... -0.18737236 -0.07576546
  -0.16134029]]
[[3.33834637 3.05200603 3.47155343 ... 4.35209951 4.62203604 2.7

 70%|███████   | 14/20 [00:31<00:13,  2.25s/it]

[[0.10325282 0.15967003 0.18956171 ... 0.2521686  0.22413863 0.15166566]
 [0.09962352 0.12970293 0.14368977 ... 0.18243199 0.15356909 0.14488222]
 [0.13796737 0.15054176 0.15162781 ... 0.12571594 0.13504276 0.11410002]
 ...
 [0.27624546 0.25402927 0.22650173 ... 0.2079583  0.23329991 0.23251558]
 [0.3343043  0.23910198 0.24507625 ... 0.33816323 0.2810946  0.23951388]
 [0.14249363 0.11585237 0.09302441 ... 0.11786288 0.15131299 0.21286782]]
[[ 0.16650558  0.19085972  0.23585281 ...  0.27363379  0.24451301
   0.25223751]
 [ 0.14215256  0.16630113  0.18286526 ...  0.16786303  0.18716093
   0.16498124]
 [ 0.21409897  0.23057867  0.25805992 ...  0.27724573  0.2873053
   0.26607978]
 ...
 [ 0.40297304  0.12453248  0.42753622 ...  0.79851488  0.25786858
   0.58255177]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.23780446 -0.16871653  0.19975678 ... -0.18831749 -0.07704973
  -0.16249569]]
[[3.33939794 3.05179043 3.47170981 ... 4.34818082 4.62206668 2.71

 75%|███████▌  | 15/20 [00:33<00:11,  2.24s/it]

[[0.1023244  0.15882795 0.18962223 ... 0.25223237 0.22387845 0.15237287]
 [0.09925818 0.12986556 0.14349689 ... 0.18236265 0.15355682 0.144793  ]
 [0.13813282 0.15081427 0.15098127 ... 0.12556927 0.13448205 0.11375629]
 ...
 [0.2763446  0.2541165  0.22632844 ... 0.20768962 0.2329629  0.23217262]
 [0.33400427 0.24012296 0.24511019 ... 0.33658068 0.28022803 0.23987288]
 [0.14235936 0.11573891 0.09341506 ... 0.11804928 0.15148321 0.21269744]]
[[ 0.16583973  0.19043864  0.23582656 ...  0.27402265  0.24487424
   0.25246477]
 [ 0.14230986  0.16653029  0.18277776 ...  0.16785267  0.18710376
   0.16486338]
 [ 0.21382466  0.23042152  0.2580925  ...  0.27733244  0.28734955
   0.26615727]
 ...
 [ 0.40225848  0.1246775   0.42679602 ...  0.79668785  0.25766683
   0.58142282]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.23581057 -0.16957067  0.19775009 ... -0.18924384 -0.07831409
  -0.16362945]]
[[3.34045411 3.0515699  3.47186638 ... 4.34423877 4.62209234 2.7

 80%|████████  | 16/20 [00:35<00:08,  2.23s/it]

[[0.1014025  0.15799954 0.1896779  ... 0.25230728 0.22363107 0.15306971]
 [0.09890042 0.13002365 0.14331079 ... 0.18229803 0.1535469  0.14470496]
 [0.138293   0.15108819 0.15034798 ... 0.12542235 0.13393614 0.11341149]
 ...
 [0.27644091 0.25420164 0.22615653 ... 0.20742123 0.23262922 0.23183194]
 [0.33371422 0.24112526 0.24514488 ... 0.33501876 0.27937224 0.2402203 ]
 [0.14222126 0.11562949 0.09380317 ... 0.11823166 0.1516482  0.21252542]]
[[ 0.16518379  0.19002409  0.23580105 ...  0.2744057   0.24523009
   0.25268798]
 [ 0.14246501  0.16675798  0.18269121 ...  0.16784267  0.18704732
   0.16474879]
 [ 0.21355474  0.23026821  0.25812402 ...  0.2774177   0.28739255
   0.26623313]
 ...
 [ 0.40154126  0.12481692  0.42605368 ...  0.79486159  0.25746089
   0.58029181]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.23383783 -0.17040552  0.19576378 ... -0.19015156 -0.07955869
  -0.16474177]]
[[3.34151421 3.05134463 3.47202292 ... 4.34027438 4.62211288 2.6

 85%|████████▌ | 17/20 [00:38<00:06,  2.24s/it]

[[0.10048713 0.1571845  0.18972894 ... 0.25239272 0.22339602 0.15375632]
 [0.09854997 0.13017734 0.14313122 ... 0.18223787 0.15353915 0.14461804]
 [0.13844788 0.15136322 0.14972758 ... 0.12527535 0.1334047  0.11306585]
 ...
 [0.27653433 0.25428465 0.22598601 ... 0.20715328 0.2322989  0.23149361]
 [0.33343384 0.24210921 0.24518024 ... 0.33347719 0.27852713 0.24055642]
 [0.14207948 0.11552397 0.09418875 ... 0.1184101  0.1518081  0.21235182]]
[[ 0.16453788  0.18961616  0.23577621 ...  0.27478281  0.24558048
   0.25290705]
 [ 0.14261799  0.16698418  0.18260559 ...  0.16783304  0.18699158
   0.16463739]
 [ 0.21328925  0.23011876  0.25815446 ...  0.27750144  0.28743427
   0.26630732]
 ...
 [ 0.40082149  0.12495086  0.42530927 ...  0.79303619  0.25725087
   0.57915886]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.23188601 -0.17122132  0.1937977  ... -0.19104081 -0.08078369
  -0.16583286]]
[[3.34257756 3.0511148  3.47217924 ... 4.33628865 4.62212819 2.6

 90%|█████████ | 18/20 [00:40<00:04,  2.28s/it]

[[0.09957829 0.15638253 0.18977557 ... 0.25248811 0.22317283 0.15443284]
 [0.09820659 0.13032674 0.14295792 ... 0.18218191 0.15353341 0.14453221]
 [0.13859739 0.15163911 0.14911973 ... 0.12512845 0.1328874  0.11271958]
 ...
 [0.27662481 0.25436545 0.22581691 ... 0.20688594 0.231972   0.2311577 ]
 [0.33316281 0.24307511 0.24521619 ... 0.33195567 0.27769258 0.24088152]
 [0.14193417 0.11542222 0.09457177 ... 0.1185847  0.15196309 0.21217669]]
[[ 0.16390212  0.18921489  0.23575196 ...  0.27515386  0.24592534
   0.25312189]
 [ 0.1427688   0.16720884  0.18252087 ...  0.16782382  0.18693656
   0.1645291 ]
 [ 0.21302822  0.22997317  0.25818382 ...  0.27758358  0.28747467
   0.26637978]
 ...
 [ 0.40009928  0.12507944  0.42456291 ...  0.79121175  0.25703686
   0.57802408]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.22995491 -0.17201827  0.19185172 ... -0.19191177 -0.08198925
  -0.16690291]]
[[3.34364349 3.05088063 3.47233514 ... 4.33228261 4.62213818 2.6

 95%|█████████▌| 19/20 [00:42<00:02,  2.31s/it]

[[0.09867601 0.15559337 0.18981799 ... 0.25259289 0.22296106 0.1550994 ]
 [0.09787005 0.13047198 0.14279065 ... 0.18212988 0.1535295  0.14444741]
 [0.1387415  0.1519156  0.14852409 ... 0.1249818  0.1323839  0.11237289]
 ...
 [0.2767123  0.25444402 0.22564924 ... 0.20661934 0.23164854 0.23082429]
 [0.33290081 0.24402328 0.24525268 ... 0.33045392 0.27686849 0.24119585]
 [0.14178548 0.11532414 0.09495225 ... 0.11875554 0.1521133  0.2120001 ]]
[[ 0.16327661  0.18882037  0.23572824 ...  0.27551874  0.24626462
   0.25333244]
 [ 0.14291742  0.16743193  0.18243704 ...  0.16781502  0.18688223
   0.16442387]
 [ 0.21277168  0.22983144  0.2582121  ...  0.27766407  0.28751373
   0.2664505 ]
 ...
 [ 0.39937475  0.12520279  0.42381467 ...  0.78938835  0.25681898
   0.57688759]
 [ 0.43429547  0.38871172  0.66850299 ...  0.58605836  0.43299575
   0.65552907]
 [ 0.22804434 -0.1727966   0.1899257  ... -0.19276458 -0.08317553
  -0.16795214]]
[[3.34471133 3.05064233 3.47249042 ... 4.32825727 4.62214277 2.6

100%|██████████| 20/20 [00:45<00:00,  2.26s/it]


In [58]:
print(test_data_matrix.shape)

(39679, 2)


In [59]:
from sklearn.metrics import mean_squared_error
from math import sqrt
def rmse(prediction, ground_truth):
    prediction = prediction[ground_truth.nonzero()].flatten()
    ground_truth = ground_truth[ground_truth.nonzero()].flatten()
    return sqrt(mean_squared_error(prediction, ground_truth))
rsme_v = rmse(res,train_data_matrix)
print(rsme_v)

0.877428053203302
